config/routes.rb
Rails.application.routes.draw do

 # config/routes.rb
  root "visits#index"

  resources :visits
  #
  # get "visits" => "visits#index"
  # get "visits"/:id => "visits#show", as: :visit
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hr.rb
class Hr < ApplicationRecord
  def self.select_options
    order(name: :asc).map do |h|
      [h.name, h.id]
    end
  end
end

app/models/visit.rb
class Visit < ApplicationRecord
  belongs_to :hr
 end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
  before_action :set_visit, only: [:show, :edit, :update, :destroy]

  # GET /visits
  # GET /visits.json
  def index
    @visits = Visit.all
  end


  # GET /visits/1
  # GET /visits/1.json
  def show
    @visit = Visit.find(params[:id])
  end

  # GET /visits/new
  def new
    @visit = Visit.new
  end

  # GET /visits/1/edit
  def edit
  end

  # POST /visits
  # POST /visits.json

  def create
     @visit = Visit.new( visit_params )

     if @visit.save
        redirect_to @visit
     else
        render 'new'
     end
  end



  # PATCH/PUT /visits/1
  # PATCH/PUT /visits/1.json
  def update
    respond_to do |format|
      if @visit.update(visit_params)
        format.html { redirect_to @visit, notice: 'Visit was successfully updated.' }
        format.json { render :show, status: :ok, location: @visit }
      else
        format.html { render :edit }
        format.json { render json: @visit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /visits/1
  # DELETE /visits/1.json
  def destroy
    @visit.destroy
    respond_to do |format|
      format.html { redirect_to visits_url, notice: 'Visit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_visit
      @visit = Visit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def visit_params
      params.require(:visit).permit(:threat, :advice, :hr_id)
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RedAnna</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/visits/_form.html.erb
<%= form_for @visit do |f| %>
    <pre><%= @visit.errors.to_json %></pre>
    <%= f.label :threat %>
    <%= f.select :threat, [['Yes', true], ['No', false]] %>

    <%= f.label :advice %>
    <%= f.select :advice, [['Yes', true], ['No', false]] %>

    <%= f.label :hr %>
    <%= f.select :hr_id, Hr.select_options %>

    <%= f.submit (@visit.new_record? ? "Create" : "Update") %>

<% end %>

<div class="container">

	<h2>Was there any threat?</h2>

  <ul>
  <li>
    <input type="radio" id="f-option" name="selector">
    <label for="f-option">Yes</label>

    <div class="check"></div>
  </li>

  <li>
    <input type="radio" id="s-option" name="selector">
    <label for="s-option">No</label>

    <div class="check"><div class="inside"></div></div>
  </li>


</ul>
</div>

app/views/visits/edit.html.erb
<h1>Editing Visit</h1>

<%= render 'form', visit: @visit %>

<%= link_to 'Show', @visit %> |
<%= link_to 'Back', visits_path %>

app/views/visits/index.html.erb
<div class="container-bg">

<p id="notice"><%= notice %></p>

<h1>Visits</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @visits.each do |visit| %>
      <tr>
        <td><%= visit.threat %></td>
        <td><%= link_to 'Show', visit %></td>
        <td><%= link_to 'Edit', edit_visit_path(visit) %></td>
        <td><%= link_to 'Destroy', visit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Visit', new_visit_path %>
</div>

app/views/visits/new.html.erb
<h1>New Visit</h1>


<%= render 'form', visit: @visit %>

<%= link_to 'Back', visits_path %>

app/views/visits/show.html.erb
<h1><%= @visit.id %></h1>



<%= link_to 'Edit', edit_visit_path(@visit) %> |
<%= link_to 'Back', visits_path %>